### ISSUE TITLE
Wild ranks not correctly tracked

### ISSUE THREAD

**Issue by sphaleron** [AdnanC/HDT.Plugins.MetaStats#2]
Player and opponent ranks are not correctly submitted when playing Wild format. Below is a snippet of cardStats.xml as saved by the plugin (and apparently also submitted to MetaStats). In this particular game, both me and my opponent were Wild rank 14 (I rose to 13 due to winning this). However, in the stats file playerRank is 16 (this is my current Standard rank).

This seems to be because the plugin is using [...].LocalPlayer.StandardRank and similar when tracking, e.g. MetaStats.cs line 432.

```
<trackCards>
    <playerClass>Druid</playerClass>
    <opponentClass>Priest</opponentClass>
    <gameFormat>Wild</gameFormat>
    <gameMode>Ranked</gameMode>
    <region>EU</region>
    <rankedSeasonId>41</rankedSeasonId>
    <opponentRank>7</opponentRank>
    <opponentLegendRank>0</opponentLegendRank>
    <opponentCoin>false</opponentCoin>
    <playerRank>16</playerRank>
    <playerLegendRank>0</playerLegendRank>
    <opponentWin>false</opponentWin>
    <playerWin>true</playerWin>
    <cardId>CFM_614e</cardId>
    <cardName>Savage Mark</cardName>
    <turn>5</turn>
    <turnDrawn>-1</turnDrawn>
    <turnToGraveyard>-1</turnToGraveyard>
    <mulligan>false</mulligan>
    <mana>-1</mana>
    <manaOverload>-1</manaOverload>
    <isCreated>true</isCreated>
    <createdBy>CFM_614</createdBy>
    <activePlayer>Player</activePlayer>
  </trackCards>
```

**Comment by AdnanC** [comment]
Nice catch. I have been working on redoing a lot of the code and I believe that should already fix it. I just haven't had a chance to push out the new version due to other commitments. I will try and get this fixed asap
